name: Python tests for ros2

on:
  # Triggered whenever push to the master branch
  push:
    branches:
      - main
      - aida

  # Triggered whenever a pull request is created on master
  pull_request:
    branches: main
    


jobs:
  build-and-test:
    runs-on: ubuntu-22.04
    strategy: 
      fail-fast: false
    steps:
    - name: Setup ROS2
      uses: ros-tooling/setup-ros@0.7.1
      with: 
        required-ros-distributions: humble
 
    - name: Checkout code
      uses: actions/checkout@v3
  
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: Install python dependancies
      run: | 
        pip install numpy
        pip install faster-whisper
        pip install librosa
        pip install sounddevice
    - name: Run build and tests
      uses: ros-tooling/action-ros-ci@0.3.7
      with:
          package-name: speech_to_text audio_data audio aida_interfaces
          target-ros2-distro: humble
    
    - name: Upload logs
      uses: actions/upload-artifact@v1
      with: 
        name: colcon-logs
        path: ros_ws/log
      if: always()
  
  
  
