name: Python tests for ros2

on:
  # Triggered whenever push to the master branch
  push:
    branches:
      - main
      - aida

  # Triggered whenever a pull request is created on master
  pull_request:
    branches: main
    

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
      fail-fast: false
    steps:
    - name: Setup ROS 2
      uses: ros-tooling/setup-ros@0.7.1
      with:
        required-ros-distributions: humble

    - name: Install Python dependencies
      run: |
        sudo apt-get update
        sudo apt-get install python3-pip
        pip install sounddevice
        pip install faster-whisper
        
    - name: Run Tests
      uses: ros-tooling/action-ros-ci@0.3.7
      with:
        target-ros2-distro: humble
        package-name: |
          aida_interfaces
          speech_to_text
          audio_data
          audio
