name: Python tests for ros2

on:
  # Triggered whenever push to the master branch
  push:
    branches:
      - main
      - aida

  # Triggered whenever a pull request is created on master
  pull_request:
    branches: main
    

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
      fail-fast: false
    steps:
    - name: Setup ROS 2
      uses: ros-tooling/setup-ros@0.7.1
      with:
        required-ros-distributions: humble

    - name: Run Tests
      uses: ros-tooling/action-ros-ci@0.3.7
      with:
        package-name: aida_interfaces

    - name: Upload Logs
      uses: actions/upload-artifact@v1
      with:
        name: colcon-logs
        path: ros_ws/log
      if: always()
