name: Python tests for ros2

on:
  # Triggered whenever push to the master branch
  push:
    branches:
      - main
      - aida

  # Triggered whenever a pull request is created on master
  pull_request:
    branches: main
    

jobs:
  build_docker:
    runs-on: ubuntu-22.04
    container:
      image: ubuntu:jammy
    steps:
    - uses: ros-tooling/setup-ros@v0.7
      with:
        required-ros-distributions: humble
        
    #- run: | 
        #source /opt/ros/humble/setup.bash
    #- run: "source /opt/ros/humble/setup.bash && ros2 run --help"
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install python dependencies
      run: | 
        pip install faster-whisper
        pip install numpy==1.24.3
        pip install sounddevice
        pip install librosa
    - name: Running tests for ROS2
      uses: ros-tooling/action-ros-ci@v0.2
      with:
        package-name: audio_package speech_to_text aida_interfaces audio
        target-ros2-distro: humble
        vcs-repo-file-url: https://raw.githubusercontent.com/ros2/ros2/humble/ros2.repos
      
        
        
        # use_ros2_testing: true
        
    

 
