name: Python tests for ros2

on:
  # Triggered whenever push to the master branch
  push:
    branches:
      - main
      - aida

  # Triggered whenever a pull request is created on master
  pull_request:
    branches: main
    

jobs:
  

  build-and-test:
    
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout
      uses: actions/checkout@v4.0.0
      with:
        path: AIDA/ros2_humble_ws
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install python dependencies
      run: | 
        pip install faster-whisper
        pip install numpy==1.24.3
        pip install sounddevice
        pip install librosa
    - name: Setup workspace
      uses: ichiro-its/ros2-ws-action/setup@v1.0.0
      with: 
        distro: humble
    
    - name: Build workspace
      uses: ichiro-its/ros2-ws-action/build@v1.0.0
      with: 
        distro: humble
    
    - name: Test workspace
      uses: ichiro-its/ros2-ws-action/test@v1.0.0
      with: 
        distro: humble
