name: Ros2 automatic testing
on: 
  push:
    branches:
      - main
      - automatic-testing
  pull_request:
    branches:
      - main
      - automatic-testing


jobs:
  build_docker:
    runs-on: ubuntu-22.04
    container:
      image: ubuntu:jammy
    steps:
      
      - uses: ros-tooling/setup-ros@v0.7
        with:
          required-ros-distributions: humble
      - run: "source /opt/ros/humble/setup.bash && ros2 run --help"
        shell: bash 

      - name: Checkout repository
        uses: actions/checkout@v4.0.0

      - name: Build ROS 2 packages
        run: colcon build
        #run: "source install/localsetup.bash"
        shell: bash

      - name: Run tests
        run: colcon test
        
