name: Ros2 automatic testing
on: 
  push:
    branches:
      - main
      - automatic-testing
  pull_request:
    branches:
      - main
      - automatic-testing


jobs:
  build_docker:
  #build_and_test:
   # name: Build and test
    runs-on: ubuntu-22.04
    container:
      #image: ubuntu:jammy
      image: osrf/ros:humble-desktop
    steps:
      
      - name: Install pip
        run: | 
          apt update
          apt install python3-pip -y

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
        working-directory: ./AIDA/ros2_humble_ws/
         
          #pip install faster-whisper
          #pip install sounddevice
          #pip install pytest
          #pip install librosa
          #pip install numpy==1.24.3

      
      
      - name: Checkout
        uses: actions/checkout@v4.0.0
        #with:
          #path: workspace
        
      - name: Build
        run: |
          source /opt/ros/humble/setup.bash
          colcon build
        shell: bash
        working-directory: ./AIDA/ros2_humble_ws/

      - name: Test
        run: |
          source /opt/ros/humble/setup.bash
          source install/local_setup.bash
          colcon test
          colcon test-result --all --verbose
        #source install/localsetup.bash
        shell: bash
        working-directory: ./AIDA/ros2_humble_ws/
        
        
        #sudo apt update
        #sudo apt install python3-pip
        #pip install -r requirements.txt  # Adjust based on your requirements file
        #working-directory: ./AIDA/ros2_humble_ws/
  
        #
      #- uses: ros-tooling/setup-ros@v0.7
      #  with:
      #    required-ros-distributions: humble
      #- run: "source /opt/ros/humble/setup.bash && ros2 run --help"
      #  shell: bash 
      #- name: Source environment
        #run: "echo source /opt/ros/humble/setup.bash >> ~/.bashrc"
      #  run: "source /opt/ros/humble/setup.bash"
      #  shell: bash
        #working-directory: ./AIDA/ros2_humble_ws/
        

      #- name: Checkout repository
      #  uses: actions/checkout@v4.0.0
      #- name: Set working directory
        #working-directory: ./AIDA/ros2_humble_ws
        #run: "source install/localsetup.bash"
        #shell: bash
      
      #- uses: ros-tooling/action-ros-ci@0.3.7
      #  with:
      #    package-name: aida_interfaces audio_package speech_to_text audio
      #    target-ros2-distro: humble
      #
      #- name: Build ROS 2 packages
      #  run: | 
      #    source /opt/ros/humble/setup.bash
      #    colcon build
      #  shell: bash
      #  working-directory: ./AIDA/ros2_humble_ws/ 

      #- name: Run tests
      #  run: | 
      #    source /opt/ros/humble/setup.bash
      #    source install/localsetup.bash
      #    colcon test
      #  shell: bash
      #  working-directory: ./AIDA/ros2_humble_ws/ 
      
