name: Ros2 automatic testing
on: 
  push:
    branches:
      - main
      - automatic-testing
  pull_request:
    branches:
      - main
      - automatic-testing


jobs:
  build_docker:
  #build_and_test:
   # name: Build and test
    runs-on: ubuntu-22.04
    #container:
      #image: ubuntu:jammy
      #image: osrf/ros:humble-desktop
    steps:
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'  # Choose the Python version you need
      - name: Install pip
        run: | 
          sudo apt update
          sudo apt install python3-pip -y

      - name: Install dependencies
        run: |
          pip install faster-whisper
          pip install sounddevice
          pip install pytest
          pip install librosa

      
      - name: Checkout repository
        uses: actions/checkout@v4.0.0

      #- name: Install ros2

      - name: Build
        run: |
          source /opt/ros/humble/setup.bash
          colcon build
        shell: bash
        working-directory: ./AIDA/ros2_humble_ws/
        
        #sudo apt update
        #sudo apt install python3-pip
        #pip install -r requirements.txt  # Adjust based on your requirements file
        #working-directory: ./AIDA/ros2_humble_ws/
  
        #
      #- uses: ros-tooling/setup-ros@v0.7
      #  with:
      #    required-ros-distributions: humble
      #- run: "source /opt/ros/humble/setup.bash && ros2 run --help"
      #  shell: bash 
      #- name: Source environment
        #run: "echo source /opt/ros/humble/setup.bash >> ~/.bashrc"
      #  run: "source /opt/ros/humble/setup.bash"
      #  shell: bash
        #working-directory: ./AIDA/ros2_humble_ws/
        

      #- name: Checkout repository
      #  uses: actions/checkout@v4.0.0
      #- name: Set working directory
        #working-directory: ./AIDA/ros2_humble_ws
        #run: "source install/localsetup.bash"
        #shell: bash
      
      #- uses: ros-tooling/action-ros-ci@0.3.7
      #  with:
      #    package-name: aida_interfaces audio_package speech_to_text audio
      #    target-ros2-distro: humble
      #
      #- name: Build ROS 2 packages
      #  run: | 
      #    source /opt/ros/humble/setup.bash
      #    colcon build
      #  shell: bash
      #  working-directory: ./AIDA/ros2_humble_ws/ 

      #- name: Run tests
      #  run: | 
      #    source /opt/ros/humble/setup.bash
      #    source install/localsetup.bash
      #    colcon test
      #  shell: bash
      #  working-directory: ./AIDA/ros2_humble_ws/ 
      
          distro: humble
      
