name: Ros2 automatic testing
on: 
  push:
    branches:
      - main
      - automatic-testing
  pull_request:
    branches:
      - main
      - automatic-testing


jobs:


  build_docker:
    runs-on: ubuntu-22.04
    container:
      image: ubuntu:jammy
    steps:
      - uses: ros-tooling/setup-ros@v0.7
        with:
          required-ros-distributions: humble
      - run: "/bin/bash/ -c source /opt/ros/humble/setup.bash && ros2 run --help"
    
