name: Ros2 automatic testing
on: 
  push:
    branches:
      - main
      - automatic-testing
  pull_request:
    branches:
      - main
      - automatic-testing


jobs:
  build_docker:
    runs-on: ubuntu-22.04
    container:
      #image: ubuntu:jammy
      image: osrf/ros:humble-desktop
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.0.0
  
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'  # Choose the Python version you need
      - name: Install pip
        run: | 
          python -m ensurepip --upgrade

      - name: Install dependencies
        run: |
          pip install faster-whisper
          pip install numpy==1.25.3
          pip install sounddevice
          pip install pytest
          pip install librosa
        #sudo apt update
        #sudo apt install python3-pip
        #pip install -r requirements.txt  # Adjust based on your requirements file
        #working-directory: ./AIDA/ros2_humble_ws/
  
        #
      #- uses: ros-tooling/setup-ros@v0.7
      #  with:
      #    required-ros-distributions: humble
      #- run: "source /opt/ros/humble/setup.bash && ros2 run --help"
      #  shell: bash 
      - name: Source environment
        run: "echo source /opt/ros/humble/setup.bash >> ~/.bashrc"
        shell: bash
        working-directory: ./AIDA/ros2_humble_ws/
        

      #- name: Checkout repository
      #  uses: actions/checkout@v4.0.0
      #- name: Set working directory
        #working-directory: ./AIDA/ros2_humble_ws
        #run: "source install/localsetup.bash"
        #shell: bash
      
      #- uses: ros-tooling/action-ros-ci@0.3.7
      #  with:
      #    package-name: aida_interfaces audio_package speech_to_text audio
      #    target-ros2-distro: humble

      - name: Build ROS 2 packages
        run: | 
          colcon build
        shell: bash
        working-directory: ./AIDA/ros2_humble_ws/ 

      - name: Run tests
        run: | 
          "source install/localsetup.bash"
          colcon test
        shell: bash
        working-directory: ./AIDA/ros2_humble_ws/ 
        
